# lightning.pytorch==2.2.4
seed_everything: 42
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger:
  - class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: models/bertimbau-ft-classifier-head/
      name: lightning_logs
      version: null
      prefix: ''
      flush_logs_every_n_steps: 100
  callbacks:
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: models/bertimbau-ft-classifier-head/checkpoint/
      filename: bertimbau-{epoch}-{val_f1:.2f}
      monitor: val_f1
      verbose: false
      save_last: null
      save_top_k: 1
      save_weights_only: false
      mode: min
      auto_insert_metric_name: true
      every_n_train_steps: null
      train_time_interval: null
      every_n_epochs: null
      save_on_train_epoch_end: null
      enable_version_counter: true
  fast_dev_run: false
  max_epochs: 3
  min_epochs: 1
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: advanced
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  n_classes: 3
  learning_rate: 0.001
  model_checkpoint: neuralmind/bert-base-portuguese-cased
  id2label:
    0: Neutro
    1: Positivo
    2: Negativo
  label2id:
    Neutro: 0
    Positivo: 1
    Negativo: 2
  class_weights:
  - 5.63462742
  - 1.01479668
  - 0.54433414
  train_last_n_layers: 2
data:
  raw_data_dir: data/raw/
  processed_data_dir: data/processed/
  batch_size: 64
  num_workers: 4
  cleaning_steps:
  - from_unicode_to_ascii
  - remove_user_from_tweet
  - remove_urls
  - remove_non_word_chars
  - remove_repeated_chars
  - remove_trailing_whitespace
  max_length: 128
  model_checkpoint: neuralmind/bert-base-portuguese-cased
ckpt_path: null
